### ISSUE TITLE
Heatsinks on TMC2209

### ISSUE THREAD

**Issue by kitcarfreak** [makerbase-mks/MKS-StepStick-Driver#4]
Hi,

TMV2209 V2.0 stepper drivers, is it supposed to put heatsink on the board? IC is on the under side where no heatsink fits and heatsink is very close to the pins with a possible short as result. Can you confirm this is the intention or is it not necessary to put em on?
![IMG_20210409_151921b](https://user-images.githubusercontent.com/74095849/114191708-01672300-994d-11eb-9f03-17a8b0ed14de.jpg)

**Comment by mks-viva** [comment]
This will not be a problem. If you are still worried, you can use a small heat sink or not install a heat sink .
